### ISSUE TITLE
tundra daemon seems to exit after opening mpv?

### ISSUE THREAD

**Issue by Hikandy** [m4tx/tundra#17]
I want to use tundra daemon instead of GUI for tracking anime and i have enabled it on startup but when i open mpv (via ani-cli), by the time the anime ends its gets exited and hence not able to track anime. I have to manually open tundra to track it. 

Steps to reproduce, enable tundra daemon command on start up, then open anime (using mpv), by the time the anime ends the tundra daemon exits (can check with ps aux | grep tundra)

**Comment by m4tx** [comment]
I've checked that with the latest Tundra git version and it seems to be working fine (however, ani-cli changed its reported anime title format, which I've already accounted for). Please check the latest (0.3.0) version which has just been released in AUR and Flathub, and please reopen the issue along with the exact anime title and episode if it still happens.
