### ISSUE TITLE
Detect anime title from xesm:url property too...

### ISSUE THREAD

**Issue by ahmubashshir** [m4tx/tundra#5]
Sometimes, videos doesn't contain metadatas like title... in these cases, tundra fails to detect the title.
ex: [Trackma MPRIS tracker](https://github.com/z411/trackma/blob/master/trackma/tracker/mpris.py)

**Comment by emekoi** [comment]
[it does.](https://github.com/m4tx/tundra/blob/f6d2d0fc473a3c5d1e5209675b4247d3befc7a3a/src/player_controller/mod.rs#L65)
